### ISSUE TITLE
how to display a file-picture?

### ISSUE THREAD

**Issue by AlanLes** [strongloop/loopback-component-storage#100]
I am using **loopback-component-storage** for uploading images to server.
https://docs.strongloop.com/display/public/LB/Storage+component

I have also AngularJS JavaScript SDK so my lb-services.js is dynamically updated.
https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK

Now I want to display in my webpage the photo from this loopback component storage model, called container, so I can use in my angular controller method  getFile (from the lb-service), which "Get information for specified file within specified container." like that:

`$scope smthing = Container.getFile({container: 'news-imgs', file: 'smallpic.png'})`

or I can use method download, which "Download a file within specified container." like that:

`$scope smthing = Container.download({container: 'news-imgs', file: 'smallpic.png'})`

in my controller.

Now, the problem is, when I will write in the .html file `{{smthing}}`, the first method will show me

 `{
  "container": "news-imgs",
  "name": "smallpic.png",
  "size": 757,
  "atime": "2015-12-01T11:49:36.840Z",
  "mtime": "2015-12-01T11:49:36.840Z",
  "ctime": "2015-12-01T11:49:36.840Z"
}`

and the second method will show so many sad signs, like this:

`"0":"�","1":"P","2":"N","3":"G","4":"\r","5":"\n","6":"\u001a","7":"\n","8":"\u0000","9":"\u0000","10":"\u0000","11":"\r","12":"I","13":"H","14":"D","15":"R","16":"\u0000","17":"\u0000","18":"\u0000","19":"\u0014","20":"\u0000","21":"\u0000","22":"\u0000","23":"\u0012","24":"\b","25":"\u0003","26":"\u0000","27":"\u0000","28":"\u0000","29":"l","30":"\u000e","31":"\u000e","32":"\"","33":"\u0000","34":"\u0000","35":"\u0000","36":"\u0019","37":"t","38":"E","39":"X","40":"t","41":"S","42":"o","43":"f","44":"t","45":"w","46":"a","47":"r","48":"e","49":"\u0000","50":"A","51":"d","52":"o","53":"b","54":"e","55":" ","56":"I","57":"m","58":"a","59":"g","60":"e","61":"R","62":"e","63":"a","64":"d","65":"y","66":"q","67":"�","68":"e","69":"<","70":"\u0000","71":"\u0000","72":"\u0001","73":"�","74":"P","75":"L","76":"T","77":"E","78":"�","79":"�","80":"�","81":"�","82":"�","83":"�","84":"�","85":"\u0000","86":"r","87":"�","88":"�","89":"�","90":"�","91":"\u0000","92":"�","93":"�","94":"\u0000","95":"~","96":"�","97":"�","98":"�","99":"�","100":"\u0000","101":"x","102":"�","103":"\u0012","104":"�","105":"�","106":"\u0000","107":"","108":"�","109":"\t","110":"�","111":"�","112":"\u0016","113":"{","114":"�","115":"\u0002","116":"�","117":"�","118":"(",...etc`

I think it's the Image object but in the json, right?

I was also trying to throw the `{{smthing}}` to `<img src="">` tag, and `<img ng-src="">`, but it doesn't work too.

The question is: how to display this photo? 

Greetings, Alan.

**Comment by richardpringle** [comment]
@AlanLes, try asking this same question in one of the following locations: 
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I haven't personally tried to do this before but I think  that it is also an application that loopback-component-storage wasn't necessarily designed for (even if it is possible), it was really only designed for file transfers.

I am going to close this issue since we are trying to reserve the issues section on GitHub for bug reports and feature requests. I think you will have better luck getting a response in one of the above mentioned locations anyway.

Sorry I couldn't help you out :disappointed:, good luck!

**Comment by z3dmax** [comment]
Do you find a solution? I've the same problem here: the response is a json object that appere like this:
�����JFIF����������C�

**Comment by richardpringle** [comment]
I believe what's going on is that your return type is `string` instead of buffer. You should just get the hex values instead of symbols. To return images, you can also "highjack" the `res` object and use `res.send` like you would in express. 

That is a bit of a workaround though, it's not really proper usage of LoopBack. LoopBack is really only built to send data. In the case of the `loopback-component-storage` you can send files, but they aren't mean to be displayed (if it's an image).

Try out `res.send` like you would with Express. If you need help figuring out how to access the `res` object, let me know and I will show you how (make sure you mention me in any comments).
