### ISSUE TITLE
Operation hook on new file created?

### ISSUE THREAD

**Issue by clearmirror** [strongloop/loopback-component-storage#104]
Right now I am using Container.afterRemote('upload') and it does the trick. But is there any operation hooks on the model level to trigger a function when a new file is created?

**Comment by richardpringle** [comment]
@clearmirror, what do you mean by "model level" here? The thing is, it's only the `container` that is recognized as a LoopBack model.

Might want to try posting to one of the following to see if someone else has attempted this before:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're trying to use the issues section of GitHub for feature requests and bug reports *only*, so I am going to close this since it's a question. You could open a feature request, but in all honesty, this repo hasn't received a whole lot of love lately (we're so busy working on other parts of LoopBack).

You could also try to implement it yourself and open up a PR :stuck_out_tongue_winking_eye:. 

In the meantime, ask around in the community and see if you can find some help there. Good luck!
