### ISSUE TITLE
Folder missing, upload receiving same response as success in Angular

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-component-storage#105]
I'm not sure if this is a design issue with error checking or a bug of another kind.

Here's a scenario that I run into from time to time.

A file is uploaded using the REST API and an incorrect container name is used.
At least in Angular with its generated js, I haven't tested it elsewhere, it receives the same response as when it successfully uploads, but the file is not in the container and has not been uploaded.

In that situation, I'd expect it would come back as an error saying "Cannot upload the file. The container does not exist" or something along those lines.

**Comment by richardpringle** [comment]
@alexxgathp, I just tried this out with [loopback-example-storage (example-2.0)](https://github.com/strongloop/loopback-example-storage) and it worked fine. Is it possible for you to upload a sandbox (you can fork [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)) or even fork the example and modify it so that the error is reproducible?

Also, could be the specific file system, which one are you using?
