### ISSUE TITLE
How to check file format before uploading a file in container?

### ISSUE THREAD

**Issue by RAJESHI2IT** [strongloop/loopback-component-storage#112]
I have tried this way (http://stackoverflow.com/questions/28885282/how-to-store-files-with-meta-data-in-loopback?answertab=votes#tab-top).
I can successfully upload the file, but before that I have to validate file type and allow only *.csv  files.

**Comment by denzelwamburu** [comment]
I think you can check the format in the front end using ngFileUpload

**Comment by RAJESHI2IT** [comment]
@denzelwamburu  I want to validate in server side since I use API.

**Comment by richardpringle** [comment]
@RAJESHI2IT 

Which answer from Stack Overflow were you looking at? The second answer has the following code:
```node
var fileInfo = fileObj.files.file[0];
File.create({
  name: fileInfo.name,
  type: fileInfo.type,
  container: fileInfo.container,
  url: CONTAINERS_URL+fileInfo.container+'/download/'+fileInfo.name
},function (err,obj) {
  if (err !== null) {
    cb(err);
  } else {
    cb(null, obj);
  }
});
```
I haven't tried this code out myself, but it looks like you can check the type beforehand, would that work?

We are actually trying to maintain the issues section on GitHub for bug reports and feature requests only, so if you could repost this question in one (or more) of the following locations, that would be much appreciated:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I am going to close this issue since it is a question but I think you will have better luck getting an answer elsewhere. In general, this is not functionality that comes out of the box (as stated in the docs). There are a few feature requests that have already been submitted that would make validation much easier.

Good luck and happy coding!

**Comment by av-k** [comment]
#richardpringle answer from another case. Actual use optional param *allowedContentTypes*.

In directory *boot* use example code:
`module.exports = function(server) {
   server.dataSources.filestorage.connector.allowedContentTypes = ["image/jpg", "image/jpeg", "image/png"]
};`

I hope it will help someone.

**Comment by richardpringle** [comment]
Thanks @av-k, would be good if you could post the same thing on [Stack Overflow](http://stackoverflow.com/questions/28885282/how-to-store-files-with-meta-data-in-loopback?answertab=votes#tab-top) as well!

**Comment by av-k** [comment]
@richardpringle, [Done](http://stackoverflow.com/a/36707925/6222707).
