### ISSUE TITLE
no way to provide content/mime type filter

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-component-storage#119]
Most backends, if not all, allow for a content type filter for uploads...which is kinda essential if you don't want users to upload malicious content. Am I missing something here? Is there any way to inspect the stream in flight or such? Or add backend configuration, i.e. for S3?

**Comment by richardpringle** [comment]
Not that I am aware of. To be completely honest, this module hasn't been a priority lately and I might even go as far as to say that it's still on the experimental side of things seeing as how these are quite a few really good feature requests like this one. 

Always welcoming PRs though if you want to take a look into it yourself!

Let me know if you're interested in submitting a PR and I will provide as much help through the process as possible! Otherwise, I'll throw a feature label on here and hope that it gets some love soon.

Thanks for the suggestion @Morriz, cheers.

**Comment by Morriz** [comment]
I will first drop the same request with pkgcloud, as you are mostly piping the stream to their code ;)
