### ISSUE TITLE
How to upload a file?

### ISSUE THREAD

**Issue by Piu130** [strongloop/loopback-component-storage#123]
How can I upload a file? I have the file in a JavaScript File()-Object. When I POST this it throws an error 500 unknow type `image/jpeg`.
When I wrap it like this `{ file: <File>, type: "image/jpeg" }` it doesn't respond.
How do I upload a file correctly?

One time I had an error where the file size was to big. Can I extend it?

**Comment by z3dmax** [comment]
Hi,
you can check out the test code here:

[L162](https://github.com/strongloop/loopback-component-storage/blob/master/test/upload-download.test.js#L162)

**Comment by superkhau** [comment]
See https://github.com/strongloop/loopback-example-storage. For future references, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by jackrobertscott** [comment]
Loopback doesn't have very clear information on how to upload files..

It's probably an issue on the back-end rather than on the front-end. The best way to receive a file is to get the file from the `req` object by using a file extractor like multiparty and then you have the file to do what ever you want from it. I wrote a little post on how to do that here: https://medium.com/@jackscott/upload-files-to-aws-s3-in-loopback-29a3f01119f4

Hope it helps! 😄
