### ISSUE TITLE
add field name into the getFilename file object

### ISSUE THREAD

**Issue by hgouveia** [strongloop/loopback-component-storage#146]
would be very useful if the file object that is pass into getFilename, have the field name too, i really need to know this information to be able to name the file base of the field name, this is very fast to implement , just need  modified 

_lib/storage-handler.js:66_
before:

```
    var file = {
      container: container,
      name: part.filename,
      type: part.mime
    };
```

after

```
    var file = {
      container: container,
      name: part.filename,
      type: part.mime,
      field: part.name //new property
    };

```

i also found this pull request : https://github.com/strongloop/loopback-component-storage/pull/121

**Comment by richardpringle** [comment]
@hgouveia, I closed the old PR due to a lack of response from the contributor. Do you want to submit a new one? 

Please make sure that the scope of the PR is clear in the description, including a link to this issue. Also, the last PR did not test to see if the new field was being populated properly, please add a test to do so if you submit the PR. 

When you are done, you can mention me in a comment and I will review the PR.

**Comment by demsey2** [comment]
hi @hgouveia any update on that PR

**Comment by hgouveia** [comment]
@demsey2 @richardpringle  yeap i already make the changes but i need to make the test cases, i will try to push the PR during this week when i have enough time :smile:

**Comment by hgouveia** [comment]
@richardpringle added PR, https://github.com/strongloop/loopback-component-storage/pull/148
