### ISSUE TITLE
FileSystemProvider: Provide setting to create the root path if it does not exist

### ISSUE THREAD

**Issue by siyb** [strongloop/loopback-component-storage#173]
Please provide a setting to auto create the root directory on FileSystemProvider creation. I would volunteer to implement this feature and send you a PR if you are accepting.

**Comment by Allan1** [comment]
+1

**Comment by siyb** [comment]
So, what's the deal? Should I implement this feature and send you guys a PR, are you dropping the issue or are you implementing it yourself?

**Comment by superkhau** [comment]
Would you like to submit a PR @siyb?

**Comment by siyb** [comment]
@superkhau: as mentioned before, I am more than willing to implement this feature, but I don't want to waste any time on it if the PR does not get accepted because the feature doesn't make sense or because no one has time to merge it. Since the issue was tagged with "needs-triage", I am uncertain if you really want the feature or not.

**Comment by superkhau** [comment]
Our need-triage label automatically applies to any new issues (as in somebody needs to look at it/respond). I don't see an issue with your proposed feature (preferably, via an optional flag so that we can preserve the old behaviour and turn on the flag for your new one -- so we don't break any existing apps or surprise people with new root dir creations).
