### ISSUE TITLE
POST from iOS client

### ISSUE THREAD

**Issue by GaryHomewood** [strongloop/loopback-component-storage#19]
How do I use the LoopBack component storage to save an image file from an iOS client?
I can see it has been added to the Android SDK:  
http://docs.strongloop.com/display/LB/Working+with+files+using+the+Android+SDK

**Comment by richardpringle** [comment]
Hey @GaryHomewood, trying to respond to all these old issues (especially ones that have been ignored like yours).

I believe that this should help https://apidocs.strongloop.com/loopback-sdk-ios/api/interface_l_b_file.html

I am going to close this issue now since it is a question.
Please post any new questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by richardpringle** [comment]
Feel free to comment in here if you have anything to add though. Just make sure you mention me in the comment to make sure that I see it!
