### ISSUE TITLE
Getting notified metadata removed so you can remove file from provider...

### ISSUE THREAD

**Issue by nowherenearithaca** [strongloop/loopback-component-storage#21]
I've got some things set up to store metadata ("uploadedFile") for an uploaded file, with it storing the container and filename in the db (this is associated with a user).

However, I can't figure out a clean way to remove the file from the provider (filesystem or cloud service) after you delete the record for uploadedFile in the db.  

I got something working using the before/afterRemote, but it seems to require setting some of the metadata on the request in beforeDelete so that you can get it back after the delete occurs and afterDelete is called, but that feels overly complicated.  

I tried using afterDestroy but it doesn't look like much is implemented for that yet - or at least I couldn't get it to work.

What is the best way to do this kind of thing with loopback?

**Comment by richardpringle** [comment]
Hey @nowherenearithaca, I am going to close this issue since it is a question.
For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

I realise this issue is super old, but if you're looking for an answer, hopefully you'll be able to find something on the Google group. Otherwise, you could actually open a new issue as a feature request. I'll point you to our wiki again for details on how to do that: https://github.com/strongloop/loopback/wiki/Reporting-issues#feature-requests

Hopefully any new issues will get a quicker response!

happy coding
