### ISSUE TITLE
Processing hook or loopback-component-image

### ISSUE THREAD

**Issue by ariskemper** [strongloop/loopback-component-storage#38]
Would be good to have a processing hook, which would be used for file manipulations for example like image resizing. Another idea is to have another component loopback-component-image, which could be used by the model created by developer. This component would use loopback-component-storage for saving file to different storage services.

**Comment by bajtos** [comment]
Use cases:

a) Whenever a new image is uploaded, the server resizes the image before it is uploaded to the storage provider.

b) Whenever a new image is uploaded, the server creates three variants (small, medium, large) and uploads these three variants to the storage provider instead of the original payload.

**Comment by seriousben** [comment]
I think this should be handle asynchronously, I don't want my API to handle this. I want specialized nodes handling image processing.

**Comment by TonyLuo** [comment]
@bajtos any update on this enhancement? looking forward to seeing it

**Comment by bajtos** [comment]
@TonyLuo I am afraid this enhancement is not our priority at the moment.

**Comment by viljami** [comment]
+1

**Comment by chillyprig** [comment]
+1
