### ISSUE TITLE
Error: Cannot resolve path "compression"

### ISSUE THREAD

**Issue by Vinay328** [strongloop/loopback-component-storage#87]
When I run node . in example - 2.0 I am getting an Error: Cannot resolve path "compression" . Does any one know how to fix this issue??

response would be highly appreciated.

**Comment by crandmck** [comment]
Did you do:
```
$ cd example-2.0
$ npm install
```
?

**Comment by hellsan631** [comment]
It sounds like you didn't include the NPM package "compression" in your project.

if the above doesn't work,

```bash
npm install --save compression
```

**Comment by crandmck** [comment]
Since [package.json](https://github.com/strongloop/loopback-component-storage/blob/master/example-2.0/package.json) has 
```
"dependencies": {
    "compression": "^1.0.3",
```
Then simply running `npm install` should install the compression module.

@Vinay328 since you didn't reply, I'll assume that either you've solved your issue or you've moved on.  If you need to continue the discussion, please reopen.
